name: 'Build and docker push'
description: 'A GitHub Action that runs docker build, and push the artifact to docker hub'
inputs:
outputs:
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Docker Build
      id: docker_build
      run: python src/docker-ci.py
      shell: bash
