name: 'Build and docker push'
description: 'A GitHub Action that runs docker build, and push the artifact to docker hub'
inputs:
  username:
    description: 'Enter your docker hub username.'
    required: True
  token:
    description: 'Enter your docker hub token.'
    required: True
  repository:
    description: 'Enter your docker hub repository.'
    required: True
  tag:
    description: 'Enter the tag name.'
    required: True
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Pass Inputs to Shell
      run: |
              echo "USERNAME=${{ inputs.username }}" >> "$GITHUB_ENV"
              echo "TOKEN=${{ inputs.token }}" >> "$GITHUB_ENV"
              echo "TAG=${{ inputs.tag }}" >> "$GITHUB_ENV"
              echo "REPOSITORY=${{ inputs.repository }}" >> "$GITHUB_ENV"
      shell: bash
    - name: Docker Build
      id: docker_build
      run: |
        pip install -r .github/requirements.txt
        python .github/docker-ci.py
      shell: bash

