name: docker-ci-build
on: [push]

jobs:
  local-test:
    runs-on: ubuntu-latest
    name: Docker build and push to docker hub repository.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker-ci-build
        id: docker-ci-build
        uses: ./
        with:
          tag: "test_action"
          repository: ${{ secrets.REPOSITORY }} 
          username: ${{ secrets.USERNAME }}
          token: ${{ secrets.TOKEN }}
